version: '3.7'
services:
  bot:
    image: brandonmoss99/telegram-tweet-media-downloader
    container_name: telegram-tweet-media-downloader
    volumes:
      - ./data:/bot/gallery-dl
      - ./etc:/etc
    restart: unless-stopped
    environment:
      # Use environment variables defined in a .env file
      - T_TOKEN=${T_TOKEN}
      - ALLOWED_IDS=${ALLOWED_IDS}
      - LOG_LEVEL=${LOG_LEVEL}
      - CHATID=${CHATID}
