name: Run tests

on: push

jobs:
  UnitTest:
    name: Run unit tests
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip' # cache pip dependencies
      
      - name: Install required dependencies
        run: pip install -r requirements.txt
      
      - name: Run unit tests
        run: python -m unittest discover -s ./src
